// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FixLiveSplit():Promise<void>;

export function GetIcon(arg1:string):Promise<string>;

export function GetOptions():Promise<Array<main.Option>>;

export function GetSplits(arg1:string):Promise<main.GetSplitsResult>;

export function GetTemplates():Promise<Array<main.Option>>;

export function GetUserDefinedFiles():Promise<Array<main.Option>>;

export function LoadSplitFile(arg1:string):Promise<main.GetSplitsResult>;

export function OnSelectUserDefinedFile(arg1:string):Promise<main.GetSplitsResult>;

export function SaveIconsZip():Promise<void>;

export function SaveSplitsFile(arg1:Array<main.SplitLine>,arg2:boolean,arg3:boolean,arg4:boolean):Promise<void>;
