// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FixLiveSplit() {
  return window['go']['main']['App']['FixLiveSplit']();
}

export function GetIcon(arg1) {
  return window['go']['main']['App']['GetIcon'](arg1);
}

export function GetOptions() {
  return window['go']['main']['App']['GetOptions']();
}

export function GetSplits(arg1) {
  return window['go']['main']['App']['GetSplits'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetUserDefinedFiles() {
  return window['go']['main']['App']['GetUserDefinedFiles']();
}

export function LoadSplitFile(arg1) {
  return window['go']['main']['App']['LoadSplitFile'](arg1);
}

export function OnSelectUserDefinedFile(arg1) {
  return window['go']['main']['App']['OnSelectUserDefinedFile'](arg1);
}

export function SaveIconsZip() {
  return window['go']['main']['App']['SaveIconsZip']();
}

export function SaveSplitsFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSplitsFile'](arg1, arg2, arg3, arg4);
}
